
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: root
  jpa:
    # Specify DBPS
    database: POSTGRESQL
    show-sql: false

    # Hibernate DDL Auto
    hibernate:
      ddl-auto: update

server:
  port: 8081
